name: Clang-Format

on:
  push:
    paths:
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.cpp'
      - '**/*.c'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.hh'
      - '.clang-format'
      - '.github/workflows/clang-format.yml'
  pull_request:
    paths:
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.cpp'
      - '**/*.c'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.hh'
      - '.clang-format'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-15

      - name: Check formatting
        run: |
          FILES=$(git ls-files '*.c' '*.cc' '*.cxx' '*.cpp' '*.h' '*.hh' '*.hpp')
          if [ -n "$FILES" ]; then
            clang-format-15 --dry-run --Werror $FILES
          fi
